source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'spring'
gem 'activeadmin', github: 'activeadmin'
gem 'inherited_resources'
gem 'devise'
gem 'faker'
gem 'newrelic_rpm'
gem 'hoptoad_notifier'
gem 'mechanize'
gem 'pg'
gem 'unicorn'
gem 'heroku-deflater'
gem 'rails_12factor'
gem 'rack-throttle'
gem 'rack-cache'
gem 'sqlite3'
gem 'factory_girl_rails'
gem 'rspec-rails'
gem 'spork'
gem 'shoulda'
gem 'shoulda-matchers'
gem 'webmock'
gem 'webrat'
gem 'simplecov'
